### ISSUE TITLE
Different file extensions on member images 

### ISSUE THREAD

**Issue by jmadin** [open-traits-network/open-traits-network.github.io#25]
Image files in images/map folder have a range of different file extensions -  e.g., jpg, jpeg, JPG, and png. Maybe someone knows some clever code to deal with this for the _layouts/member.html file. Otherwise, I'm afraid we will need to standardize these.

**Comment by jhpoelen** [comment]
@jmadin I've renamed / converted the member images to use ```[member.id].jpg``` names, using kebab-case. Also, I moved the images into /images/member/ . I imagine that the images are not only used for the map. Please also note that the json representation of the members is now included via ```_includes/members.js``` to avoid code duplication.

**Comment by jhpoelen** [comment]
@jmadin I've added the member image selection to [_includes/members.js](_includes/members.js) . Perhaps we can re-use this logic in the [_layouts/member.html] page also. See attached screenshot.

![Screenshot from 2019-09-17 09-29-54](https://user-images.githubusercontent.com/1084872/65061159-3278a080-d92e-11e9-8865-9d9f0699d0a2.png)

**Comment by bmaitner** [comment]
Interesting note:  I don't currently have a photo in images/members, but Brian Enquist's photo shows when I click my dot on the map (along with my text).  Is this a fuzzy matching thing?

![image](https://user-images.githubusercontent.com/11130881/65064224-dcf3c200-d934-11e9-9e50-122b444f543a.png)

**Comment by iimog** [comment]
Cool progress. It's hard to keep pace :+1: I included the paths to the images in all the member `.md` files this morning but wanted to test before I open a pull request. Seems like this is no longer necessary with the unified naming scheme for member images. It would be redundant to store the `image` path in the `yml` header explicitly. @bmaitner your image was probably missing because you have the `github` header set which should have added your profile picture. Seems like you fixed this issue for yourself by uploading a picture. But for @rachaelgallagher the picture shown currently belongs to Peter Manning :grimacing:
I will further inspect. As a side note: images missing this morning were:
```
brian-s-maitner
daniel-s-falster
florian-d-schneider
jorrit-h-poelen
rachael-v-gallagher
```

**Comment by iimog** [comment]
The wrong image issue is fixed.

**Comment by jhpoelen** [comment]
@iimog note that https://github.com/open-traits-network/open-traits-network.github.io/blob/master/_includes/members.js has logic to pick an image with using a github profile image as fall-back. I was hoping we can re-use that logic in the member.html template.

**Comment by iimog** [comment]
Thanks @jhpoelen you are right, this is a great idea. And it is definitely possible. Currently, however the code still generates an html string inside a javascript object that is part of an array (of pins, so only members with coordinates are included). We might want to abstract this even more (e.g. to store images in a javascript object with member id as key and resolved image path as value. Or even outside of javascript as a jekyll/liquid function (I have no experience with that). Do you know how to do that? Otherwise I can take a shot at it tomorrow.

I also checked again and images in the `images/members` folder are missing now for: 
 - `daniel-s-falster`
 - `florian-d-schneider` (@fdschneider is also missing from the map as the coordinates are missing as well)
 - `jorrit-h-poelen` (github account linked)
 - `rachael-v-gallagher` (github account linked)

**Comment by jhpoelen** [comment]
@iimog sounds doable and curious to see what you or others come up with.

**Comment by rachaelgallagher** [comment]
Fantastic progress on all this everyone! perhaps it's best to simply upload images for those still missing rather than using linked git images @iimog ?

**Comment by iimog** [comment]
@rachaelgallagher I think it is a good idea to have this multi-stage approach to find a suitable profile picture for the future (see #27 for the current implementation). However, there are advantages to have the images in the `images/members` folder, e.g. quicker load time so for the four members with missing images it is probably best to add images for them anyway.

**Comment by jhpoelen** [comment]
@iimog thanks again for generalizing member image loading. With this, we can easily simplify or add logic and apply it across all the member images across the site. I like the approach of keeping refactoring (see https://martinfowler.com/books/refactoring.html) separate from changing functionality.

Am closing issue now, because I feel the original issue has been addressed. Please feel free to re-open / comment if more work is needed on this.
